#!/bin/sh -e

# I hereby place this script in the public domain -- Colin Percival

#TODO: Add an entry for the IP address: ie. "dig +short A $HOST"

# Usage
if [ $# -lt 2 ]; then
	echo "usage: $0 host ~/.ssh/known_hosts [fingerprints ...]" >/dev/stderr
	exit 1;
fi

# Extract host name from command line.
HOST=$1
shift;

# Extract known_hosts filename from command line.
KNOWN_HOSTS=$1
shift;

# Print a warning if no fingerprints were provided.
if [ $# -lt 1 ]; then
	echo "$0: No fingerprints provided for host $HOST" >/dev/stderr
	exit 0;
fi

# Create a directory for our temporary files.
D=`mktemp -d "${TMP:-/tmp}/ssh-knownhost.XXXXXX"` || exit 1

# No good keys yet.
: > $D/goodkeys

# Handle SSH keys of various sorts.
for KTYPE in rsa1 rsa dsa ecdsa; do
	ssh-keyscan -t $KTYPE $HOST > $D/hostkey.$KTYPE 2>/dev/null || {
		echo "\033[1;33mUnable to get $KTYPE hostkey from $HOST, aborting.\033[0m"
		rm $D/hostkey.$KTYPE
		rm $D/goodkeys
		rmdir $D
		exit 1
	}
	if [ -s $D/hostkey.$KTYPE ]; then
		KPRINT=`ssh-keygen -lf $D/hostkey.$KTYPE | cut -f 2 -d ' '`
		GOODKEY=0
		for KEY in "$@"; do
			if [ "$KEY" = "$KPRINT" ]; then
				GOODKEY=1
			fi
		done
		if [ $GOODKEY = 1 ]; then
			cat $D/hostkey.$KTYPE >> $D/goodkeys
		#else
		#	echo "$0: $KTYPE key for $HOST not in provided list"
		#	>/dev/stderr
		fi
	fi
	rm $D/hostkey.$KTYPE
done

# Add new keys to our known_hosts file.
if [ -s "$D/goodkeys" ]; then
  sort < $D/goodkeys > $D/goodkeys.tmp
  mv $D/goodkeys.tmp $D/goodkeys

  if [ ! -e $KNOWN_HOSTS ]; then
    cat $D/goodkeys > $KNOWN_HOSTS
    if [ ! -e $KNOWN_HOSTS ]; then
      rm $D/goodkeys
      rmdir $D
      echo "\033[1;33mUnable to write to $KNOWN_HOSTS, aborting\033[0m"
      exit 1
    fi
    rm $D/goodkeys
  else
    sort < $KNOWN_HOSTS | comm -13 - $D/goodkeys > $D/newkeys
    cat $D/newkeys >> $KNOWN_HOSTS
    rm $D/goodkeys $D/newkeys
  fi
  ssh-keygen -H -f $KNOWN_HOSTS 2> /dev/null
  rm $KNOWN_HOSTS.old
  rmdir $D
  echo "\033[1;32mAdded fingerprint $@ for $HOST to $KNOWN_HOSTS\033[0m"
  exit 0
else
  rm $D/goodkeys
  rmdir $D
  echo "\033[1;33mHost key fingerprint for $HOST didn't match $@\033[0m"
  exit 1
fi

